// Date pentru fiecare scriitor, folosite în pagina Scriitor.jsx
const scriitoriData = {
  eminescu: {
    nume: 'Mihai Eminescu',
    date: '1850 – 1889',
    img: '/scriitori/eminescu_mihai.png',
    color: 'rgba(122,58,0,0.82)',
    banner: '/Banner/eminescu.png',
  },
  creanga: {
    nume: 'Ion Creangă',
    date: '1837 – 1889',
    img: '/scriitori/creanga_ion.png',
    color: 'rgba(255,179,71,0.82)',
    banner: '/Banner/creanga.jpg',
  },
  caragiale: {
    nume: 'I.L. Caragiale',
    date: '1852 – 1912',
    img: '/scriitori/il-caragiale.png',
    color: 'rgba(255,179,71,0.82)',
    banner: '/Banner/caragiale.png',
  },
  slavici: {
    nume: 'Ioan Slavici',
    date: '1848 – 1925',
    img: '/scriitori/ioan_slavici.png',
    color: 'rgba(122,58,0,0.82)',
    banner: '/Banner/slavici.png',
  },
  rebreanu: {
    nume: 'Liviu Rebreanu',
    date: '1885 – 1944',
    img: '/scriitori/liviu_rebreanu_nou.png',
    color: 'rgba(255,179,71,0.82)',
    banner: '/Banner/rebreanu.png',
  },
  calinescu: {
    nume: 'George Călinescu',
    date: '1899 – 1965',
    img: '/scriitori/george_calinescu.png',
    color: 'rgba(255,179,71,0.82)',
    banner: '/Banner/calinescu.png',
  },
  petrescu: {
    nume: 'Camil Petrescu',
    date: '1894 – 1957',
    img: '/scriitori/camil_rezerva.png',
    color: 'rgba(122,58,0,0.82)',
    //banner: '/Banner/wmremove-transformed.png',
  },
  barbu: {
    nume: 'Ion Barbu',
    date: '1895 – 1961',
    img: '/scriitori/barbu_ion.png',
    color: 'rgba(255,179,71,0.82)',
    //banner: '/Banner/wmremove-transformed.png',
  },
  blaga: {
    nume: 'Lucian Blaga',
    date: '1895 – 1961',
    img: '/scriitori/lucian_blaga.png',
    color: 'rgba(122,58,0,0.82)',
    //banner: '/Banner/wmremove-transformed.png',
  },
  arghezi: {
    nume: 'Tudor Arghezi',
    date: '1880 – 1967',
    img: '/scriitori/tudor_arghezi.png',
    color: 'rgba(255,179,71,0.82)',
    //banner: '/Banner/wmremove-transformed.png',
  },
  bacovia: {
    nume: 'George Bacovia',
    date: '1881 – 1957',
    img: '/scriitori/bacovia_rezerva.png',
    color: 'rgba(122,58,0,0.82)',
    //banner: '/Banner/wmremove-transformed.png',
  },
  sadoveanu: {
    nume: 'Mihail Sadoveanu',
    date: '1880 – 1961',
    img: '/scriitori/mihail-sadoveanu-3.png',
    color: 'rgba(255,179,71,0.82)',
    //banner: '/Banner/wmremove-transformed.png',
  },
  preda: {
    nume: 'Marin Preda',
    date: '1922 – 1980',
    img: '/scriitori/marin_preda.png',
    color: 'rgba(122,58,0,0.82)',
    //banner: '/Banner/wmremove-transformed.png',
  },
  stanescu: {
    nume: 'Nichita Stănescu',
    date: '1933 – 1983',
    img: '/scriitori/nichita_stanescu_rezerva.png',
    color: 'rgba(255,179,71,0.82)',
    //banner: '/Banner/wmremove-transformed.png',
  },
  sorescu: {
    nume: 'Marin Sorescu',
    date: '1936 – 1996',
    img: '/scriitori/marin_sorescu.png',
    color: 'rgba(122,58,0,0.82)',
    //banner: '/Banner/wmremove-transformed.png',
  },
  maiorescu: {
    nume: 'Titu Maiorescu',
    date: '1840 – 1917',
    img: '/scriitori/titu_maiorescu (2).png',
    color: 'rgba(122,58,0,0.82)',
    //banner: '/Banner/wmremove-transformed.png',
  },
  eliade: {
    nume: 'Mircea Eliade',
    date: '1907 – 1986',
    img: '/scriitori/mircea-eliade.png',
    color: 'rgba(255,179,71,0.82)',
    //banner: '/Banner/wmremove-transformed.png',
  },
  negruzzi: {
    nume: 'Costache Negruzzi',
    date: '1808 – 1868',
    img: '/scriitori/costache-negruzzi.png',
    color: 'rgba(255,179,71,0.82)',
    //banner: '/Banner/wmremove-transformed.png',
  },
  pillat: {
    nume: 'Ion Pillat',
    date: '1891 – 1945',
    img: '/scriitori/ion_pillat.png',
    color: 'rgba(122,58,0,0.82)',
    //banner: '/Banner/wmremove-transformed.png',
  },
  voiculescu: {
    nume: 'Vasile Voiculescu',
    date: '1884 – 1963',
    img: '/scriitori/vasile_voiculescu.png',
    color: 'rgba(255,179,71,0.82)',
    //banner: '/Banner/wmremove-transformed.png',
  },
};

export default scriitoriData; 